format = """
$os\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$character"""
[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
# success_symbol = "[#](purple)"
# error_symbol = "[#](red)"
# vimcmd_symbol = "[#](green)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style="#14a5ae"
symbol = "\ue0a0"

[git_status]
# format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed )]($style)"
style = "cyan"
conflicted = "⇡⇣"
# untracked = " ✩"
untracked = "?"
modified = "*"
staged = " "
renamed = "➜"
deleted = "✖"
stashed = "≡"

# [git_state]
# format = '\([$state($progress_current/$progress_total)]($style)\)'
# style = "bright-black"

[aws]
symbol = "  "

[bun]
format = "[$symbol]($style)"

[buf]
format = "[$symbol]($style)"
symbol = " "

[cmake]
format = "[$symbol]($style)"

[c]
format = "[$symbol($version(-$name) )]($style)"
symbol = " "

[cobol]
format = "[$symbol]($style)"

[crystal]
format = "[$symbol]($style)"

[daml]
format = "[$symbol]($style)"

[dart]
format = "[$symbol]($style)"

[deno]
format = "[$symbol]($style)"

[dotnet]
format = "[$symbol(🎯 $tfm )]($style)"

[elixir]
format = '[$symbol]($style)'

[elm]
format = '[$symbol]($style)'

[erlang]
format = '[$symbol]($style)'

[fennel]
format = '[$symbol]($style)'

[gleam]
format = '[$symbol]($style)'

[guix_shell]
symbol = " "

[golang]
format = '[$symbol]($style)'

[gradle]
format = '[$symbol]($style)'

[haskell]
symbol = " "

[haxe]
format = '[$symbol]($style)'

[helm]
format = '[$symbol]($style)'

[java]
format = '[$symbol]($style)'

[julia]
format = '[$symbol]($style)'

[kotlin]
format = '[$symbol]($style)'

[lua]
format = '[$symbol]($style)'

[meson]
format = '[$symbol]($style)'

[nim]
format = '[$symbol]($style)'

[nix_shell]
symbol = " "

[nodejs]
format = '[$symbol]($style)'

[ocaml]
format = '[$symbol(\($switch_indicator$switch_name\) )]($style)'

[opa]
format = '[$symbol]($style)'

[perl]
format = '[$symbol]($style)'

[php]
format = '[$symbol]($style)'

[pulumi]
format = '[$symbol$stack]($style)'

[purescript]
format = '[$symbol]($style)'

[python]
format = '[$symbol]($style)'

[quarto]
format = '[$symbol]($style)'

[raku]
format = '[$symbol]($style)'

[red]
format = '[$symbol]($style)'

[rlang]
format = '[$symbol]($style)'

[ruby]
format = '[$symbol]($style)'

[rust]
format = '[$symbol]($style)'

[solidity]
format = '[$symbol]($style)'

[typst]
format = '[$symbol]($style)'

[swift]
format = '[$symbol]($style)'

[vagrant]
format = '[$symbol]($style)'

[vlang]
format = '[$symbol]($style)'

[zig]
format = '[$symbol]($style)'

[username]
show_always = true
style_user="#43e8bb bold"
format="[\ueb99 $user on ]($style)"

[os]
disabled=true

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[directory]
format = "[ $path]($style)[$read_only]($read_only_style) "
truncation_length = 3
read_only = " 󰌾"

[package]
disabled=true

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
